name: Deploy PDF to GitHub Pages

on:
  push:
    branches:
      - main


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cv .

      - name: Run container
        run: docker run --name cv_container cv

      - name: Copy PDF from container
        run: docker cp cv_container:/app/main.pdf resume.pdf

      - name: Prepare pages folder
        run: |
          mkdir public
          cp resume.pdf public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'