name: Deploy PDF to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cv .

      - name: Run container
        run: docker run --name cv_container cv

      - name: Copy PDF from container
        run: |
          docker cp cv_container:/cv/CV/main.pdf resume.pdf
          docker rm cv_container

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          # Создаём отдельную папку для PDF
          mkdir -p public
          cp resume.pdf public/
          git add public/resume.pdf
          git commit -m "Deploy resume PDF"
          git push origin gh-pages --force